# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347e145f0b24b7c4bd224826704ec5682a5965d57d8b82afb92a648609d6b1dc5908ad2e1d7cc29044550257dc208edbb6b6c407a52741081a91e81436cf0676

test:
  secret_key_base: c403bc1b59643e0962d99c161fe5c89da90789b38d08b11168b6dc97ba50a6e7875720c0785c975f215b2a715d412bb96078f5623c59520975901db919e570c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
